# SQLite version 3.x
# gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: sqlite3
  database: db/development.sqlite3

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: resume_test
  username: postgres
  password: 123123

production:
  adapter: sqlite3
  database: db/development.sqlite3

cucumber:
  <<: *TEST

